rules = [
  OrganizeImports
]

OrganizeImports {
  groups = [
    "re:java\\..*"
    "re:scala\\..*"
    "re:javax\\..*"
    "re:org\\.scala-lang\\..*"
    "*"
  ]

  importSelectorsOrder = Ascii
  removeUnused = true
  targetDialect = Scala3
  blankLines = Auto
  expandRelative = false
  groupSeparately = [ByTypeGivens]
  groupedImports = Merge
}
